#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group tevvo.
groups:
  - ubuntu: [root,sys]
  - tevvo

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: myuser
    gecos: myuser
    shell: /bin/bash
    primary_group: tevvo
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false